core/urls.py
from django.urls import path
from.views import about,Work,home,contact, WorkDetailView, ProjectView

app_name='core'
urlpatterns = [
	path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('list/', Work.as_view(), name='project_list'),
    path('<slug>/', WorkDetailView.as_view(), name='project'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls',namespace='core'))
]


if settings.DEBUG:
	urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.shortcuts import reverse
from PIL import Image

class MyWork(models.Model):
	title = models.CharField(max_length=200)
	image = models.ImageField(upload_to='Mywork')
	slug  = models.SlugField()

	def __str__(self):
		return self.title

	def get_absolute_url(self ,*args, **kwargs):
		return reverse("core:project", kwargs={
		'slug':self.slug
		})


	@property
	def projects(self):
		return self.project_set.all().order_by('position')


	def save(self,*args, **kwargs):
		super().save(*args, **kwargs)

		img = Image.open(self.image.path)

		if img.height > 750 or img.width>1400:
			output_size =(750, 1400)
			img.thumbnail(output_size)
			img.save(self.image.path)
		else:
			pass

class Project(models.Model):
	title       = models.CharField(max_length=100)
	image       = models.ImageField(upload_to='Projects')
	work        = models.ForeignKey(MyWork, on_delete=models.CASCADE)
	description = models.TextField()
	url         = models.URLField()
	position    = models.IntegerField()
	slug        = models.SlugField()

	def __str__(self):
		return self.title

	def get_absolute_url(self,*args, **kwargs):
		return reverse('core:project', kwargs={
		    "work_slug":self.work.slug,
			# "slug":self.slug
			})
	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)

		img = Image.open(self.image.path)

		if img.height > 750 or img.width>1400:
			output_size =(750, 1400)
			img.thumbnail(output_size)
			img.save(self.image.path)
		else:
			pass

class ProfilePicture(models.Model):
	image = models.ImageField(upload_to='profiles')
	title = models.CharField(max_length= 100)

	def __str__(self):
		return self.title

	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)

		image_croped = Image.open(self.image.path)

		if image_croped.height > 250 or image_croped.width>250:
			output_size = (250,250)
			image_croped.thumbnail(output_size)
			image_croped.save(self.image.path)
		else:
			pass

core/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Project, MyWork, ProfilePicture

def about(request):
    profile = ProfilePicture.objects.all()

    context = {
        'profile':profile
    }
    return render(request, "core/about.html", context)

def contact(request):
    profile = ProfilePicture.objects.all()
    context={
        'profile':profile
    }
    return render(request, "core/contact.html",context)

def home(request):
    return render(request, "core/index.html")

class Work(ListView):
    model = MyWork
    template_name = "core/work.html"

class WorkDetailView(DetailView):
    model = MyWork
    template_name = "core/work_detail.html"

class ProjectView(DetailView):
	model = Project
	template_name="core/project.html"

core/templates/core/about.html
{%extends "core/layout.html"%}
{%load static%}
{%block content%}

  <main id="about">
    <h1 class="lg-heading">
      About
      <span class="text-warning">Me</span>
    </h1>
    <h2 class="sm-heading">
      Let me tell you a few things...
    </h2>
    <div class="about-info">
      <img src="{%static "dist/img/mundia5.jpg"%}" alt="John Doe" class="bio-image">

      <div class="bio">
        <h3 class="text-warning">BIO</h3>
        <p>Mundia Pizo is a web developer and mobile app developer, He is also an artificial intelligence and data science engineer, He is an Electrical Electronics and telecommunications Engineer. Below are some of the skills he has and expertise. </p>
      </div>

      <div class="job job-1">
        <h3 class="mb-3">Electrical, Elelctronics and Telecommunications Engineer</h3>
        <p>I am an Electronics and Telecommunications engineer, bachelors Degree Holder. Am also a robotic enthusiate. </p>
      </div>

      <div class="job job-2">
        <h3 class="mb-3">Full stack Developer</h3>
        <i class="fab fa-html5 fa-4x text-primary"></i>
        <i class="fab fa-react fa-4x text-info"></i>

         <i class="fab fa-angular fa-4x text-danger"></i>
         <i class="fab fa-vuejs fa-4x text-info"></i>
         <i class="fab fa-python fa-4x text-info"></i>
        <p>I also develop responsive UI's using javascript, Html, CSS and React. Also learning angular and Vue for front end development. </p>
      </div>

      <div class="job job-3">
        <h3 class="mb-3">Mobile app and Graphic Designer</h3>
        <i class="fab fa-photoshop-cc fa-4x text-info"></i>
        <p>I am also a Mobile app developer laveraging flutter, React Natve, java and c# with graphic designing skills.</p>
      </div>
    </div>
  </main>

 {%endblock content%}

core/templates/core/contact.html
{%extends "core/layout.html"%}
{%load static%}
{%block content%}
<body>
  <main id="contact">
    <h1 class="lg-heading">
      Contact
      <span class="text-warning">Me</span>
    </h1>
    <div class="about-info">
    <img src="{%static "dist/img/mundia5.jpg"%}" alt="John Doe" class="bio-image">
    <div class="bio col-md-8">
    <h3>
      For more details you can contact me on the following contacts. will be glad to hear from you and to work with you on that stunning project. Customer satisfaction is my esteem.
    </h3>
    </div>
    </div>
    <h2 class="sm-heading">
      This is how you can reach me...
    </h2>
    <div class="boxes">
      <div>
        <span class="text-warning">Email: </span> mundiapizos@gmail.com
      </div>
      <div>
        <span class="text-warning">Phone: </span> (+260) 975676504
      </div>
      <div>
        <span class="text-warning">Address: </span> The University Of Zambia P.O 32379 Lusaka Zambia, c/o Professor Mundia Muya.
      </div>
    </div>
  </main>

{%endblock content%}

core/templates/core/index.html
{%extends "core/layout.html"%}
{%load static%}
{%block content%}
<body id="bg-img">
  
  <main id="home">
    <h1 class="lg-heading">
      Mundia
      <span class="text-warning">Pizo</span>
    </h1>
    <h3 class="lg-heading">
      UI/UX
      <span class="text-warning">Designer</span>
      </h3>
      <i class="fab fa-html5 fa-4x text-primary"></i>
      <i class="fab fa-react fa-4x text-info"></i>
      <i class="fab fa-angular fa-4x text-danger"></i>
      <i class="fab fa-vuejs fa-4x text-info"></i>
    <div class=" ">
      <div class="icons space-icons">
      <a href="#!">
        <i class="fab fa-twitter fa-3x text-info"></i>
      </a>
      <a href="https://web.facebook.com/stacym.pizo.9">
        <i class="fab fa-facebook fa-3x text-primary"></i>
      </a>
      <a href="https://www.linkedin.com/in/mundia-pizo-0921b6147/">
        <i class="fab fa-linkedin fa-3x text-primary"></i>
      </a>
      <a href="https://github.com/Mundia-Pizo">
        <i class="fab fa-github fa-3x text-white-50"></i>
      </a>
    </div>
    <h2 class="sm-heading">
     Full stack Web Developer,Artificial intelligence Programmer, Mobile app developer/Designer & Entrepreneur
    </h2>
     </div>
  </main>
{%endblock content%}

core/templates/core/layout.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ"
    crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'dist/css/main.css'%}">
  <title>Mundia's Portfolio</title>
</head>
<body>
  {%include "core/menu.html"%}

	{%block content%}{%endblock%}
</body>

<footer id="main-footer">
    Copyright &copy; 2018
  </footer>

  <script src="{%static 'dist/js/main.js'%}"></script>
</body>

</html>

core/templates/core/menu.html
 <header>
    <div class="menu-btn">
      <div class="btn-line"></div>
      <div class="btn-line"></div>
      <div class="btn-line"></div>
    </div>

    <nav onmouseout="closeMenu()" class="menu">
      <div id="menuDiv" onmouseout="closeMenu()" class="menu-branding">
        <div class="portrait"></div>
      </div>
      <ul class="menu-nav">
        <li class="nav-item">
          <a href="{% url 'core:home'%}" class="nav-link">
            Home
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'core:about' %}" class="nav-link">
            About Me
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url  'core:project_list' %}" class="nav-link">
            Projects
          </a>
        </li>
        <li class="nav-item ">
          <a href="{% url  'core:contact' %}" class="nav-link">
            Contact Me
          </a>
        </li>
      </ul>
    </nav>
  </header>

core/templates/core/work.html
{%extends "core/layout.html"%}
{%load static%}
{%block content%}
  <main id="work">
    <h1 class="lg-heading">
      My
      <span class="text-warning">Work</span>
    </h1>
    <h2 class="sm-heading">
      Check out my works in different technologies...
    </h2>
    <div class="row">
      {%for object in object_list%}
         <div class="col-md-6">
           <div class="work-style">
             <div class="item">
                <h3 class="mb-3">{{object.title}}</h3>
                <a href="{{object.get_absolute_url}}">
                   <img src="{{object.image.url}}" alt="Project" class="project-images-on">
                </a>
                <a href="{{object.get_absolute_url}}" class="btn-light btn-style1">
                   <i class="fas fa-eye"></i> Project
                </a>
            </div>
          </div>
         </div>
      {%endfor%}
   </div>
  </main>

 {%endblock content%}

core/templates/core/work_detail.html
{%extends "core/layout.html"%}
{%load static%}
{%block content%}
  <main id="work">
    <h1 class="lg-heading">
      My
      <span class="text-warning">Projects</span>
    </h1>
    <h2 class="sm-heading">
      Check out some of my projects...
    </h2>
    <h1 class="text-warning mb-5">{{object.title}}</h1>
    <div class="row">
      {%for project in object.projects.all%}
        <div class="col-md-6 mb-2">
          <div class="work-style">
            <div class="item">
              <h2 class="mb-3">{{project.title}}</h2>
                <img src="{{project.image.url}}" alt="Project" class="project-images-on">
               <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                 Tempora, facilis, quos cum illo at quae nulla laboriosam possimus
                 repudiandae perferendis vero in adipisci iusto deserunt nesciunt quaerat ad ducimus a.</p>
              <a href="{{project.url}}" class="btn-dark btn-style1 mb-5">
                <i class="fab fa-github"></i> Github
              </a>
            </div>
            </div>
            </div>
            {%endfor%}
          </div>
  </main>

 {%endblock content%}